name: Publish to NPM and GPR

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
        scope: '@fawldev'
    - run: echo "`jq '.name="@fawldev/sentinel"' package.json`" > package.json
    - run: npm ci
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        registry-url: 'https://npm.pkg.github.com'
        scope: '@fawlapp'
    - run: npm ci
    - run: echo "`jq '.name="@fawlapp/sentinel"' package.json`" > package.json
    - run: echo registry=https://npm.pkg.github.com/fawlapp >> .npmrc
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}